force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <description>Represents a beer that is distributed by a brewery.</description>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_In__c/Check_In__c.object-meta.xml
<CustomObject>
    <description>Represents an instance of a beer being checked-in on Untappd.</description>
    <label>Check-In</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Check-In Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check-Ins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_In__c/fields/Beer__c.field-meta.xml
<CustomField>
    <fullName>Beer__c</fullName>
    <description>Beer that was checked in.</description>
    <label>Beer</label>
    <referenceTo>Beer__c</referenceTo>
    <relationshipName>Check_Ins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/ai/working/classes/UntappdRepository.cls
/**
 * Responsible for reading and writing data in the context of Untappd.
 */
public interface UntappdRepository {
  /**
   * Upserts the given {@link UntappdBrewery} as an {@link Account}.
   */
  Account upsertBrewery(UntappdBrewery brewery);

  /**
   * Upserts the given {@link UntappdBeer}s as {@link Beer__c} records.
   */
  List<Beer__c> upsertBeers(List<UntappdBeer> beers);

  /**
   * Upserts the given {@link UntappdCheckIn}s as {@link Check_In__c} records.
   */
  List<Check_In__c> upsertCheckins(List<UntappdCheckIn> checkIns);
}