force-app/main/default/objects/Account/fields/Untappd_Id__c.field-meta.xml
<CustomField>
    <fullName>Untappd_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier used in the Untappd API.</description>
    <externalId>true</externalId>
    <label>Untappd Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <description>Represents a beer that is distributed by a brewery.</description>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_In__c/Check_In__c.object-meta.xml
<CustomObject>
    <description>Represents an instance of a beer being checked-in on Untappd.</description>
    <label>Check-In</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Check-In Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check-Ins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_In__c/fields/Beer__c.field-meta.xml
<CustomField>
    <fullName>Beer__c</fullName>
    <description>Beer that was checked in.</description>
    <label>Beer</label>
    <referenceTo>Beer__c</referenceTo>
    <relationshipName>Check_Ins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check_In__c/fields/Untappd_Id__c.field-meta.xml
<CustomField>
    <fullName>Untappd_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier used in the Untappd API.</description>
    <externalId>true</externalId>
    <label>Untappd Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/ai/working/classes/UntappdRepositoryImpl.cls
/**
 * Implementation of {@link UntappdRepository}.
 */
public class UntappdRepositoryImpl implements UntappdRepository {
  public Account upsertBrewery(UntappdBrewery brewery) {
    Account accountToUpsert = brewery.toSObject();
    // Explicitly include Untappd_Id__c in the upsert statement
    upsert accountToUpsert Untappd_Id__c;
    return accountToUpsert;
  }

  public List<Beer__c> upsertBeers(List<UntappdBeer> beers) {
    List<Beer__c> sobjBeers = new List<Beer__c>();
    for (UntappdBeer beer : beers) {
      sobjBeers.add(beer.toSObject());
    }
    // Explicitly include Untappd_Id__c in the upsert statement
    upsert sobjBeers Untappd_Id__c;
    return sobjBeers;
  }

  public List<Check_In__c> upsertCheckins(List<UntappdCheckIn> checkIns) {
    List<Check_In__c> sobjCheckIns = new List<Check_In__c>();
    for (UntappdCheckIn checkIn : checkIns) {
      sobjCheckIns.add(checkIn.toSObject());
    }
    // Explicitly include Untappd_Id__c in the upsert statement
    upsert sobjCheckIns Untappd_Id__c;
    return sobjCheckIns;
  }
}